# -*- coding: utf-8 -*-
# See LICENSE file for full copyright and licensing details.
{
    'name': 'Core Textile System',
    'version': '10.0.1.0.0',
    'author': 'Hashmicro - Arya',
    'maintainer': 'Hashmicro - Arya',
    'category': 'Tools',
    'license': 'AGPL-3',
    'complexity': 'Hard',
    'depends': ['web','branch','product','account_asset','sale','stock','sales_team','account','account_deposit','base','purchase','hr','vit_kelurahan','membership','tax_extension','report','stock_by_location','sg_partner_payment','giro_std'],
    'summary': 'Sale-Stock Management',
    #'images': ['static/description/Digital_Signature.jpg'],
    'description': '''
        Last Update 09-11-2020
         Textile Management
    ''',
    'data': [
            'security/security.xml',
            'security/ir.model.access.csv',
            'data/cutting_data.xml',
            'views/templates.xml',
            'views/res_company_view.xml',
            'views/res_users_view.xml',
            'views/branch_view.xml',
            'views/product_view.xml',
            'views/stock_view.xml',
            'views/sale_view.xml',
            'views/product_pricelist_view.xml',
            'views/material_cutting_view.xml',
            'views/sample_request_view.xml',
            'views/lot_view.xml',
            'views/partner_view.xml',
            'views/payment_view.xml',
            'views/account_view.xml',
            'views/purchase_view.xml',
            #'views/internal_move_view.xml',
            'views/material_dictionary_view.xml',
            'views/pickup_view.xml',
            'views/delivery_view.xml',
            'views/fleet_view.xml',
            'views/operator_view.xml',
            'wizards/wizard_check_product_view.xml',
            'wizards/wizard_packing_view.xml',
            'wizards/wizard_membercard_view.xml',
            'wizards/wizard_sale_line_view.xml',
            'wizards/wizard_cancel_view.xml',
            'wizards/stock_picking_return_views.xml',
            
            'reports/layout_templates.xml',
            
            'reports/customer_deposit_templates.xml',
            'reports/packing_barcode_templates.xml',
            'reports/multipacking_barcode_templates.xml',
            'reports/asset_barcode_templates.xml',
            'reports/pengambilan_templates.xml',
            'reports/pengambilanA4_templates.xml',
            'reports/returA4_templates.xml',
            'reports/courier_deliveryA4_templates.xml',
            'reports/deliveryA4_templates.xml',
            'reports/invoice_templates.xml',
            'reports/lot_barcode_pack_templates.xml',
            'reports/lot_barcode_templates.xml',
            'reports/membercard_templates.xml',
            'reports/sample_templates.xml',
            'reports/quotation_templates.xml',
            'reports/goodsreceive_templates.xml',
            'reports/internalmove_templates.xml',
            'reports/courier_delivery_templates.xml',
            'reports/delivery_templates.xml',
            'reports/reports.xml',
        ],
    'website': 'http://www.hashmicro.com',
    #'qweb': ['static/src/xml/digital_sign.xml'],
    'installable': True,
    'auto_install': False,
}
